### PR TITLE
Update to 1.18.2 using paperweight-userdev

### PR DESCRIPTION
**Pull request by F0Xde**
Perfect for gorgeous looks, can push asap

### CODE REVIEW

**Comment by copyandexecute** [comment]
WOW THIS IS SO GREAT

**Comment by copyandexecute** [comment]
I DIRETCLY ACCEPTED IT OMG!!!

**Comment by F0Xde** [comment]
THX MAN APPRECIATE IT

**Comment by copyandexecute** [comment]
WOW I MERGED IT UNBEVLIEABLE 
KEEP THE HEAD UP

**Comment by F0Xde** [comment]
YES SIR I WILL KEEP IT UP, YOURS KINDLY

**Pull request merged**
